config_version = "0"

exclude_patterns = ["**/node_modules/**"]
test_patterns = ["**/test/**"]

[[source]]
name = "default"
default = true

[smells.function_parameters]
threshold = 5

[[exclude]]
file_patterns = ["src/_cpp/libs/**"] #Ignore all SDL files
